### PR TITLE
Feature - configparser (rewrite) and made codebase PEP compliant

### PR DESCRIPTION
**Pull request by bang-uin**
- Rewrite of the configuration module and made it a singleton class. 
- Adopted all code to match new configuration singleton
- Formatted, corrected and fixed whole codebase according to PEP
- Added FIXMEs for unresolved references

This branch is based on "[container reuse](https://github.com/bang-uin/honssh/commits/feature/container_reuse)" see https://github.com/tnich/honssh/pull/100

### CODE REVIEW

**Comment by unixfox** [comment]
Is it normal to have commits from other pull requests?
PS: Thank you for the work you put on honSSH ;).

**Comment by bang-uin** [comment]
Yes it is. As long as the other pull requests are not merged they will show up in every pull requests which is based on them.

**Comment by tnich** [comment]
Hey @bang-uin,

So, I merged your other 2 pull requests (awesome work) and made some changes of my own as I went... Can you rebase this one please?

Cheers!

**Comment by bang-uin** [comment]
Thanks for merging the other ones! 
Absolutely right, to move the docker stuff.

Rebase: There you go. Hope i didn't miss something.

**Pull request merged**
