### PR TITLE
Connection timeout for pre and post handlers and missing ssh_banner warning

### PR DESCRIPTION
**Pull request by bang-uin**

### CODE REVIEW

**Comment by bang-uin** [comment]
Hi,

There is only one connection_timeout. It is located in the general config section. The specific honeypot types do only pass the config var through to pre and post handler. 

I did it that way because i don't wanted to introduce config to pre and post handlers and to be able to have special handling in the honeypot types, just in case it is needed in the future.

**Comment by bang-uin** [comment]
I can change it if you prefer to read the config in pre and post auth handlers.

**Comment by tnich** [comment]
Ah fair enough, that makes sense 👍

**Comment by tnich** [comment]
Can you rebase the changes? They are conflicting with the other docker pull request recently 😄 
Also, can you apply the timeout to honeypot-script.py too please?

**Comment by bang-uin** [comment]
Sure. But i spotted one thing which i would like to discuss before.
In `honeypot-docker.py` at `get_post_auth_details` the line `details = self.get_connection_details()` looks to me as it will start a second container, as `get_connection_details` contains the code to launch a container upon pre_auth. Looking at the logs is see 2 different container IDs showing up. This seems to be a bug which i would fix with my next commit. Do you agree with that?

**Comment by tnich** [comment]
Yeah, it does do this currently. It was the easiest way to allow pre-auth with one plugin, and post-auth with docker.  Happy to consider other ideas though.

**Comment by bang-uin** [comment]
Hmm, i see.` pre_auth_handler` and `post_auth_handler` do hold their own list of plugins, so a plugin instance reuse is not possible without changing that, right? I thought of doing a check on `self.container` in `honeypot-docker.py->get_post_auth_details` to omit a second container launch if one is already running for that session.

**Comment by tnich** [comment]
In get_post_auth_details I'll add an if to check the cfg file for honeypot-docker - pre-auth. If that is true then don't launch the new one.

I'll commit your bits then get on doing that.

**Comment by bang-uin** [comment]
Not sure that will work as post_auth_handler needs the connection details which aren't present if no second container is launched.

**Comment by tnich** [comment]
I think it gets passed the details in conn_details, so we just need to return that (after changing the username and password fields from spoofing.

**Comment by bang-uin** [comment]
What it gets passed is 
`self.conn_details = {'peer_ip':self.server.peer_ip, 'peer_port':self.server.peer_port, 'local_ip':self.server.local_ip, 'local_port':self.server.local_port, 'username':username, 'password':password}`

But post_auth_hanlder wants:
```
self.sensor_name = returned_conn_details['sensor_name']
self.honey_ip = returned_conn_details['honey_ip']
self.honey_port = returned_conn_details['honey_port']
self.username = returned_conn_details['username']
self.password = returned_conn_details['password']
```

"sensor_name" (right now the container ID) would be missing in that case as the information is not available.
What about "honey_ip" and "honey_port"?

**Comment by tnich** [comment]
Just adding them in now, and I changed the container ID to be the hostname instead 😄

**Comment by bang-uin** [comment]
:D

**Comment by tnich** [comment]
Just pushing a commit now, seems to be ok for me.

**Comment by bang-uin** [comment]
hmpf. merged the upstream right now, added the new docker pid config from default and cannot start anymore. `create_host_config() got an unexpected keyword argument cpuset_cpus`. Need to look into that first.

**Comment by unixfox** [comment]
@bang-uin You've to update your configuration manually (`honssh.cfg`) to the latest version: https://github.com/tnich/honssh/blob/master/honssh.cfg.default#L192

**Comment by tnich** [comment]
and maybe update docker-py?

**Comment by DeltaEvolution** [comment]
@bang-uin update you docker-py version

**Comment by bang-uin** [comment]
@unixfox: i already done this "... added the new docker pid config from default ..."
@tnich: yeah that's my next try

**Comment by bang-uin** [comment]
Updated docker-py and got past the cpuset error but now the plugin throws an error "[PLUGIN][HONEYPOT-DOCKER][ERR] - ". I have no time now and will look later at this. Maybe just another config problem. Thanks.

**Comment by DeltaEvolution** [comment]
@bang-uin @unixfox had same error and it was a configuration problem :)

**Comment by tnich** [comment]
Sounds like we might need to add some checks for whatever configuration error it is

**Comment by unixfox** [comment]
@bang-uin Paste your configuration here. 
To resolve my issue I removed the `HONEYPOT DOCKER` block then I repaste the default block from the `honssh.cfg.default` and finally I filled all the fields inside the `HONEYPOT DOCKER` block.

**Comment by bang-uin** [comment]
Here: http://pastebin.com/JyXQafsx
I just copy/paste the new config entries.

**Comment by bang-uin** [comment]
Removing the old docker section and replacing it by a copy from honssh.cfg.default didn't help.
I'll remove my config and copy the default one. We'll see.

**Comment by unixfox** [comment]
Strange, here is my configuration if you need it: http://hastebin.com/ibozucevax.ini

**Comment by bang-uin** [comment]
@unixfox Which version of docker-py have you installed?
My curent version is 1.10.6

**Comment by unixfox** [comment]
@bang-uin 
````
root@honeypot:~/honssh# pip show docker-py
Name: docker-py
Version: 1.10.6
Summary: Python client for Docker.
Home-page: https://github.com/docker/docker-py/
Author: Joffrey F
Author-email: joffrey@docker.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: backports.ssl-match-hostname, six, websocket-client, ipaddress, docker-pycreds, requests
````

**Comment by bang-uin** [comment]
I don't know, but something is wrong. I've done a fresh clone from master, used the default config and just added the minimum config values to get it started using docker and the same error appears.

**Comment by unixfox** [comment]
Did you tried to fill the same field for docker customization as me?
I hope if a field isn't fill, it isn't used for launching the container because some of them requires a recent kernel (+4.4).
I ran this [Docker check](https://github.com/docker/docker/raw/master/contrib/check-config.sh) if you want to compare the results:
````
root@honeypot:~# bash check-config.sh 
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-4.4.0-45-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: missing
    (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled (as module)
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: enabled (as module)
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled (as module)
      - CONFIG_XFRM_ALGO: enabled (as module)
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled (as module)
  - "ipvlan":
    - CONFIG_IPVLAN: enabled (as module)
  - "macvlan":
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_DUMMY: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled (as module)
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

root@honeypot:~# uname -a
Linux honeypot 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
````

Between we should probably create an issue for your problem instead of resolving the issue inside a pull request.

**Comment by bang-uin** [comment]
I'm pretty sure it has something to do with the environment. Anyway, you're right. Let's stop the discussion in this pull request. I'll reinstall the VM and hope the best. If i'm not able to resolve this i'll create an issue. Thanks so far.

**Comment by bang-uin** [comment]
Just for Info:
The problem seems to come from being unable to start the docker container. For whatever reason there is no error at all. I tried everything (using unifox cfg, delete all docker images and pulling again, reinstalling all docker relevant things, ...) but nothing helped. In the end i kicked the whole VM away and starting again from scratch. Now everything seems to work. Really strange. Anyway, it's working!

**Pull request merged**
